# Generated by Django 4.2.17 on 2025-01-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_dailysummary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weighthistory',
            name='is_estimated',
            field=models.BooleanField(default=False, help_text='True for estimated entries'),
        ),
    ]
