# Generated by Django 4.2.17 on 2025-01-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_weighthistory_is_estimated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeightHistory',
        ),
    ]
